# Site settings
title: The Road Less Traveled
SEOTitle: The Road Less Traveled | The Road Less Traveled
header-img: "img/Home.jpg"
email: xiaohanyang0120@gmail.com
description: "关于读书，音乐与电影，偶尔黑客."
keyword: "杨晓寒, 博客, 互联网"
url: "https://yangxiaohan0120.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# 自定义永久链接
permalink: /blog/:year/:month/:day/:title/

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: MINO的向日葵_
zhihu_username:  Nevermind
github_username:  Yangxiaohan0120
twitter_username:  yxh02946796
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Multiple Comment System Support
comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default.
  # Available values: disqus | disqusjs | changyan | livere | gitalk | utterances
  active: gitalk
  # Setting `true` means remembering the comment system selected by the visitor.
  storage: true
  # Lazyload all comment systems.
  lazyload: false
  # Modify texts or order for any navs, here are some examples.
  nav:
    gitalk:
     order: -2
    disqusjs:
     text: Load Disqus
     order: -1


# gitalk settings
gitalk:
  enable: true  #启用gitalk
  owner: 'Yangxiaohan0120'
  github_id:  'Yangxiaohan0120' #github帐号 例：CodeHaotian
  # id: location.pathname  #此设置参照下文常见问题说明
  repo: 'Yangxiaohan0120.github.io'  #存放评论的仓库名称
  client_id:  '27ab6265b4a2124d158c' #application的id，即上文Client ID
  client_secret: '822f5ac59aad88a6c8e2b97c0333c82c32f30577' #application的密码，即上文Client Secret
  admin_user: 'Yangxiaohan0120' #页面显示联系**初始化评论 例：CodeHaotian
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN


# Disqus settings
# disqus_username: xhYang

# Netease settings
# netease_comment: false

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-EHKPJPFCKN'            # Format: UA-xxxxxx-xx
ga_domain: yangxiaohan0120.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "杨晓寒"
sidebar-avatar: https://raw.githubusercontent.com/Yangxiaohan0120/Yangxiaohan0120.github.io/main/img/avatar-xiaohan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
#         title: "乱序（Midare）",
#         href: "http://mida.re/"
#     },{
#         title: "Sherry Woo",
#         href: "https://sherrywoo.me/"
#     },{
#         title: "Kun Qian",
#         href: "http://kunq.me"
#     },{
#         title: "Ebn Zhang",
#         href: "http://ebnbin.com/"
#     },{
#         title: "SmdCn",
#         href: "http://blog.smdcn.net"
#     },{
#         title: "JiyinYiyong",
#         href: "http://tiye.me/"
#     },{
#         title: "DHong Say",
#         href: "http://dhong.co"
#     },{
        title: "Hux's Blog",
        href: "https://huangxuan.me/"
    }
]
